sudo: required
services:
 - docker

before_install:
 - docker build -t vimr/docker-react -f Dockerfile.dev .

script:
 - docker run vimr/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "ap-south-1"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-ap-south-1-774946556713"
 on:
   branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: "$AWS_SECRET_KEY"

# Empty line added to trigger Travis build.
